
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class BattleInstance : Luban.BeanBase
{
    public BattleInstance(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["scene"].IsString) { throw new SerializationException(); }  Scene = _buf["scene"]; }
        { var __json0 = _buf["friend"]; if(!__json0.IsArray) { throw new SerializationException(); } Friend = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Friend.Add(__v0); }   }
        { var __json0 = _buf["friend_pos"]; if(!__json0.IsArray) { throw new SerializationException(); } FriendPos = new System.Collections.Generic.List<vector2>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { vector2 __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.vector2.Deserializevector2(__e0);  }  FriendPos.Add(__v0); }   }
        { var __json0 = _buf["enmey"]; if(!__json0.IsArray) { throw new SerializationException(); } Enmey = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Enmey.Add(__v0); }   }
        { var __json0 = _buf["enemy_pos"]; if(!__json0.IsArray) { throw new SerializationException(); } EnemyPos = new System.Collections.Generic.List<vector2>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { vector2 __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.vector2.Deserializevector2(__e0);  }  EnemyPos.Add(__v0); }   }
        { var __json0 = _buf["enemy_refresh_time"]; if(!__json0.IsArray) { throw new SerializationException(); } EnemyRefreshTime = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  EnemyRefreshTime.Add(__v0); }   }
        { var __json0 = _buf["enemy_refresh_num"]; if(!__json0.IsArray) { throw new SerializationException(); } EnemyRefreshNum = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  EnemyRefreshNum.Add(__v0); }   }
        { var __json0 = _buf["enemy_refresh_radius"]; if(!__json0.IsArray) { throw new SerializationException(); } EnemyRefreshRadius = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  EnemyRefreshRadius.Add(__v0); }   }
    }

    public static BattleInstance DeserializeBattleInstance(JSONNode _buf)
    {
        return new BattleInstance(_buf);
    }

    /// <summary>
    /// 关卡id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 场景预制
    /// </summary>
    public readonly string Scene;
    /// <summary>
    /// 友方
    /// </summary>
    public readonly System.Collections.Generic.List<int> Friend;
    /// <summary>
    /// 友方位置
    /// </summary>
    public readonly System.Collections.Generic.List<vector2> FriendPos;
    /// <summary>
    /// 敌方
    /// </summary>
    public readonly System.Collections.Generic.List<int> Enmey;
    /// <summary>
    /// 敌方位置
    /// </summary>
    public readonly System.Collections.Generic.List<vector2> EnemyPos;
    /// <summary>
    /// 刷新时间
    /// </summary>
    public readonly System.Collections.Generic.List<int> EnemyRefreshTime;
    /// <summary>
    /// 刷新数量
    /// </summary>
    public readonly System.Collections.Generic.List<int> EnemyRefreshNum;
    /// <summary>
    /// 刷新数量
    /// </summary>
    public readonly System.Collections.Generic.List<int> EnemyRefreshRadius;
   
    public const int __ID__ = 1105190285;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "scene:" + Scene + ","
        + "friend:" + Luban.StringUtil.CollectionToString(Friend) + ","
        + "friendPos:" + Luban.StringUtil.CollectionToString(FriendPos) + ","
        + "enmey:" + Luban.StringUtil.CollectionToString(Enmey) + ","
        + "enemyPos:" + Luban.StringUtil.CollectionToString(EnemyPos) + ","
        + "enemyRefreshTime:" + Luban.StringUtil.CollectionToString(EnemyRefreshTime) + ","
        + "enemyRefreshNum:" + Luban.StringUtil.CollectionToString(EnemyRefreshNum) + ","
        + "enemyRefreshRadius:" + Luban.StringUtil.CollectionToString(EnemyRefreshRadius) + ","
        + "}";
    }
}
}

