
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class BuffEffectData : Luban.BeanBase
{
    public BuffEffectData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["effect_type"].IsNumber) { throw new SerializationException(); }  EffectType = _buf["effect_type"]; }
        { if(!_buf["param1"].IsNumber) { throw new SerializationException(); }  Param1 = _buf["param1"]; }
        { if(!_buf["param2"].IsNumber) { throw new SerializationException(); }  Param2 = _buf["param2"]; }
        { if(!_buf["param3"].IsNumber) { throw new SerializationException(); }  Param3 = _buf["param3"]; }
        { if(!_buf["param4"].IsNumber) { throw new SerializationException(); }  Param4 = _buf["param4"]; }
        { if(!_buf["param5"].IsNumber) { throw new SerializationException(); }  Param5 = _buf["param5"]; }
    }

    public static BuffEffectData DeserializeBuffEffectData(JSONNode _buf)
    {
        return new BuffEffectData(_buf);
    }

    /// <summary>
    /// BuffEffectId
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 效果类型
    /// </summary>
    public readonly int EffectType;
    /// <summary>
    /// 参数1
    /// </summary>
    public readonly float Param1;
    /// <summary>
    /// 参数2
    /// </summary>
    public readonly float Param2;
    /// <summary>
    /// 参数3
    /// </summary>
    public readonly float Param3;
    /// <summary>
    /// 参数4
    /// </summary>
    public readonly float Param4;
    /// <summary>
    /// 参数5
    /// </summary>
    public readonly float Param5;
   
    public const int __ID__ = 2114378158;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "effectType:" + EffectType + ","
        + "param1:" + Param1 + ","
        + "param2:" + Param2 + ","
        + "param3:" + Param3 + ","
        + "param4:" + Param4 + ","
        + "param5:" + Param5 + ","
        + "}";
    }
}
}

