
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class BuffData : Luban.BeanBase
{
    public BuffData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["buff"].IsNumber) { throw new SerializationException(); }  Buff = _buf["buff"]; }
        { if(!_buf["name"].IsNumber) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["des"].IsNumber) { throw new SerializationException(); }  Des = _buf["des"]; }
        { var __json0 = _buf["required_tags"]; if(!__json0.IsArray) { throw new SerializationException(); } RequiredTags = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  RequiredTags.Add(__v0); }   }
        { var __json0 = _buf["excluded_tags"]; if(!__json0.IsArray) { throw new SerializationException(); } ExcludedTags = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  ExcludedTags.Add(__v0); }   }
        { if(!_buf["duration"].IsNumber) { throw new SerializationException(); }  Duration = _buf["duration"]; }
        { if(!_buf["tick_interval"].IsNumber) { throw new SerializationException(); }  TickInterval = _buf["tick_interval"]; }
        { if(!_buf["stacking_type"].IsNumber) { throw new SerializationException(); }  StackingType = _buf["stacking_type"]; }
        { if(!_buf["max_stacks"].IsNumber) { throw new SerializationException(); }  MaxStacks = _buf["max_stacks"]; }
        { var __json0 = _buf["effects"]; if(!__json0.IsArray) { throw new SerializationException(); } Effects = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Effects.Add(__v0); }   }
    }

    public static BuffData DeserializeBuffData(JSONNode _buf)
    {
        return new BuffData(_buf);
    }

    /// <summary>
    /// buffid
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 标签，1buff，2debuff
    /// </summary>
    public readonly int Buff;
    public readonly int Name;
    public readonly string Icon;
    public readonly int Des;
    /// <summary>
    /// 需要的tag
    /// </summary>
    public readonly System.Collections.Generic.List<int> RequiredTags;
    /// <summary>
    /// 排除的tags
    /// </summary>
    public readonly System.Collections.Generic.List<int> ExcludedTags;
    /// <summary>
    /// 秒
    /// </summary>
    public readonly float Duration;
    public readonly float TickInterval;
    /// <summary>
    /// 叠加规则
    /// </summary>
    public readonly int StackingType;
    /// <summary>
    /// 叠加层数
    /// </summary>
    public readonly int MaxStacks;
    public readonly System.Collections.Generic.List<int> Effects;
   
    public const int __ID__ = -1458391363;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "buff:" + Buff + ","
        + "name:" + Name + ","
        + "icon:" + Icon + ","
        + "des:" + Des + ","
        + "requiredTags:" + Luban.StringUtil.CollectionToString(RequiredTags) + ","
        + "excludedTags:" + Luban.StringUtil.CollectionToString(ExcludedTags) + ","
        + "duration:" + Duration + ","
        + "tickInterval:" + TickInterval + ","
        + "stackingType:" + StackingType + ","
        + "maxStacks:" + MaxStacks + ","
        + "effects:" + Luban.StringUtil.CollectionToString(Effects) + ","
        + "}";
    }
}
}

