
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class BulletData : Luban.BeanBase
{
    public BulletData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["speed"].IsNumber) { throw new SerializationException(); }  Speed = _buf["speed"]; }
        { if(!_buf["res"].IsString) { throw new SerializationException(); }  Res = _buf["res"]; }
        { if(!_buf["track_type"].IsNumber) { throw new SerializationException(); }  TrackType = _buf["track_type"]; }
        { if(!_buf["source_node"].IsString) { throw new SerializationException(); }  SourceNode = _buf["source_node"]; }
        { if(!_buf["source_offset"].IsObject) { throw new SerializationException(); }  SourceOffset = global::cfg.vector3.Deserializevector3(_buf["source_offset"]);  }
        { if(!_buf["target_node"].IsString) { throw new SerializationException(); }  TargetNode = _buf["target_node"]; }
        { if(!_buf["target_offset"].IsObject) { throw new SerializationException(); }  TargetOffset = global::cfg.vector3.Deserializevector3(_buf["target_offset"]);  }
        { if(!_buf["hit_effect"].IsNumber) { throw new SerializationException(); }  HitEffect = _buf["hit_effect"]; }
    }

    public static BulletData DeserializeBulletData(JSONNode _buf)
    {
        return new BulletData(_buf);
    }

    /// <summary>
    /// 子弹ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 飞行速度
    /// </summary>
    public readonly int Speed;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Res;
    /// <summary>
    /// 移动类型：1水平追踪；2抛物线追踪
    /// </summary>
    public readonly int TrackType;
    /// <summary>
    /// 自身挂点
    /// </summary>
    public readonly string SourceNode;
    /// <summary>
    /// 自身位置前后偏移
    /// </summary>
    public readonly vector3 SourceOffset;
    /// <summary>
    /// 目标挂点
    /// </summary>
    public readonly string TargetNode;
    /// <summary>
    /// 目标位置前后偏移
    /// </summary>
    public readonly vector3 TargetOffset;
    /// <summary>
    /// 命中特效
    /// </summary>
    public readonly int HitEffect;
   
    public const int __ID__ = -1791863828;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "speed:" + Speed + ","
        + "res:" + Res + ","
        + "trackType:" + TrackType + ","
        + "sourceNode:" + SourceNode + ","
        + "sourceOffset:" + SourceOffset + ","
        + "targetNode:" + TargetNode + ","
        + "targetOffset:" + TargetOffset + ","
        + "hitEffect:" + HitEffect + ","
        + "}";
    }
}
}

