
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class CharacterData : Luban.BeanBase
{
    public CharacterData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["res"].IsString) { throw new SerializationException(); }  Res = _buf["res"]; }
        { if(!_buf["radius"].IsNumber) { throw new SerializationException(); }  Radius = _buf["radius"]; }
        { if(!_buf["search_distance"].IsNumber) { throw new SerializationException(); }  SearchDistance = _buf["search_distance"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = _buf["type"]; }
        { if(!_buf["attack"].IsNumber) { throw new SerializationException(); }  Attack = _buf["attack"]; }
        { if(!_buf["hp"].IsNumber) { throw new SerializationException(); }  Hp = _buf["hp"]; }
        { if(!_buf["move_speed"].IsNumber) { throw new SerializationException(); }  MoveSpeed = _buf["move_speed"]; }
        { var __json0 = _buf["skills"]; if(!__json0.IsArray) { throw new SerializationException(); } Skills = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Skills.Add(__v0); }   }
        { var __json0 = _buf["passive_skills"]; if(!__json0.IsArray) { throw new SerializationException(); } PassiveSkills = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  PassiveSkills.Add(__v0); }   }
    }

    public static CharacterData DeserializeCharacterData(JSONNode _buf)
    {
        return new CharacterData(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 资源
    /// </summary>
    public readonly string Res;
    /// <summary>
    /// 碰撞半径
    /// </summary>
    public readonly float Radius;
    /// <summary>
    /// 初始索敌距离
    /// </summary>
    public readonly float SearchDistance;
    /// <summary>
    /// 角色类型：1主角；2建筑
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly int Attack;
    /// <summary>
    /// 血量
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 移动速度
    /// </summary>
    public readonly int MoveSpeed;
    /// <summary>
    /// 技能组
    /// </summary>
    public readonly System.Collections.Generic.List<int> Skills;
    /// <summary>
    /// 技能组
    /// </summary>
    public readonly System.Collections.Generic.List<int> PassiveSkills;
   
    public const int __ID__ = -991456685;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "res:" + Res + ","
        + "radius:" + Radius + ","
        + "searchDistance:" + SearchDistance + ","
        + "type:" + Type + ","
        + "attack:" + Attack + ","
        + "hp:" + Hp + ","
        + "moveSpeed:" + MoveSpeed + ","
        + "skills:" + Luban.StringUtil.CollectionToString(Skills) + ","
        + "passiveSkills:" + Luban.StringUtil.CollectionToString(PassiveSkills) + ","
        + "}";
    }
}
}

