
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Effect : Luban.BeanBase
{
    public Effect(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["res"].IsString) { throw new SerializationException(); }  Res = _buf["res"]; }
        { if(!_buf["effect_type"].IsNumber) { throw new SerializationException(); }  EffectType = _buf["effect_type"]; }
        { if(!_buf["parent_node"].IsString) { throw new SerializationException(); }  ParentNode = _buf["parent_node"]; }
        { if(!_buf["pos_offset"].IsObject) { throw new SerializationException(); }  PosOffset = global::cfg.vector3.Deserializevector3(_buf["pos_offset"]);  }
        { if(!_buf["loop"].IsBoolean) { throw new SerializationException(); }  Loop = _buf["loop"]; }
        { if(!_buf["time"].IsNumber) { throw new SerializationException(); }  Time = _buf["time"]; }
    }

    public static Effect DeserializeEffect(JSONNode _buf)
    {
        return new Effect(_buf);
    }

    /// <summary>
    /// 特效id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 特效名字
    /// </summary>
    public readonly string Res;
    /// <summary>
    /// 挂点类型<br/>1：骨骼<br/>2：场景
    /// </summary>
    public readonly int EffectType;
    /// <summary>
    /// 挂点
    /// </summary>
    public readonly string ParentNode;
    /// <summary>
    /// 位置偏移
    /// </summary>
    public readonly vector3 PosOffset;
    /// <summary>
    /// 循环
    /// </summary>
    public readonly bool Loop;
    /// <summary>
    /// 持续时间(毫秒)
    /// </summary>
    public readonly int Time;
   
    public const int __ID__ = 2072749489;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "res:" + Res + ","
        + "effectType:" + EffectType + ","
        + "parentNode:" + ParentNode + ","
        + "posOffset:" + PosOffset + ","
        + "loop:" + Loop + ","
        + "time:" + Time + ","
        + "}";
    }
}
}

