
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Language : Luban.BeanBase
{
    public Language(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["Chinese"].IsString) { throw new SerializationException(); }  Chinese = _buf["Chinese"]; }
        { if(!_buf["English"].IsString) { throw new SerializationException(); }  English = _buf["English"]; }
    }

    public static Language DeserializeLanguage(JSONNode _buf)
    {
        return new Language(_buf);
    }

    /// <summary>
    /// key
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 语言
    /// </summary>
    public readonly string Chinese;
    /// <summary>
    /// 语言
    /// </summary>
    public readonly string English;
   
    public const int __ID__ = -1548945544;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "Chinese:" + Chinese + ","
        + "English:" + English + ","
        + "}";
    }
}
}

