
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class PassiveSkillData : Luban.BeanBase
{
    public PassiveSkillData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsNumber) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["des"].IsNumber) { throw new SerializationException(); }  Des = _buf["des"]; }
        { if(!_buf["event_type"].IsNumber) { throw new SerializationException(); }  EventType = _buf["event_type"]; }
        { if(!_buf["ratio"].IsNumber) { throw new SerializationException(); }  Ratio = _buf["ratio"]; }
        { if(!_buf["cooldown"].IsNumber) { throw new SerializationException(); }  Cooldown = _buf["cooldown"]; }
        { var __json0 = _buf["skill_event"]; if(!__json0.IsArray) { throw new SerializationException(); } SkillEvent = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  SkillEvent.Add(__v0); }   }
    }

    public static PassiveSkillData DeserializePassiveSkillData(JSONNode _buf)
    {
        return new PassiveSkillData(_buf);
    }

    /// <summary>
    /// 技能id
    /// </summary>
    public readonly int Id;
    public readonly int Name;
    public readonly string Icon;
    public readonly int Des;
    /// <summary>
    /// 目标类型
    /// </summary>
    public readonly int EventType;
    public readonly float Ratio;
    /// <summary>
    /// 冷却时间
    /// </summary>
    public readonly float Cooldown;
    /// <summary>
    /// 技能事件
    /// </summary>
    public readonly System.Collections.Generic.List<int> SkillEvent;
   
    public const int __ID__ = 1032891988;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "icon:" + Icon + ","
        + "des:" + Des + ","
        + "eventType:" + EventType + ","
        + "ratio:" + Ratio + ","
        + "cooldown:" + Cooldown + ","
        + "skillEvent:" + Luban.StringUtil.CollectionToString(SkillEvent) + ","
        + "}";
    }
}
}

