
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class SkillAction : Luban.BeanBase
{
    public SkillAction(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["action_type"].IsNumber) { throw new SerializationException(); }  ActionType = _buf["action_type"]; }
        { if(!_buf["time"].IsNumber) { throw new SerializationException(); }  Time = _buf["time"]; }
        { if(!_buf["target_type"].IsNumber) { throw new SerializationException(); }  TargetType = _buf["target_type"]; }
        { if(!_buf["area_center"].IsNumber) { throw new SerializationException(); }  AreaCenter = _buf["area_center"]; }
        { if(!_buf["area_radius"].IsNumber) { throw new SerializationException(); }  AreaRadius = _buf["area_radius"]; }
        { if(!_buf["bullet"].IsNumber) { throw new SerializationException(); }  Bullet = _buf["bullet"]; }
        { if(!_buf["buffId"].IsNumber) { throw new SerializationException(); }  BuffId = _buf["buffId"]; }
        { if(!_buf["ratio"].IsNumber) { throw new SerializationException(); }  Ratio = _buf["ratio"]; }
        { if(!_buf["effect"].IsNumber) { throw new SerializationException(); }  Effect = _buf["effect"]; }
        { if(!_buf["audio"].IsNumber) { throw new SerializationException(); }  Audio = _buf["audio"]; }
    }

    public static SkillAction DeserializeSkillAction(JSONNode _buf)
    {
        return new SkillAction(_buf);
    }

    /// <summary>
    /// 技能id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 效果类型
    /// </summary>
    public readonly int ActionType;
    /// <summary>
    /// 毫秒
    /// </summary>
    public readonly int Time;
    /// <summary>
    /// 1.目标，2.范围
    /// </summary>
    public readonly int TargetType;
    public readonly int AreaCenter;
    public readonly float AreaRadius;
    /// <summary>
    /// 子弹
    /// </summary>
    public readonly int Bullet;
    /// <summary>
    /// buffId
    /// </summary>
    public readonly int BuffId;
    /// <summary>
    /// 比例
    /// </summary>
    public readonly float Ratio;
    public readonly int Effect;
    public readonly int Audio;
   
    public const int __ID__ = -912385081;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "actionType:" + ActionType + ","
        + "time:" + Time + ","
        + "targetType:" + TargetType + ","
        + "areaCenter:" + AreaCenter + ","
        + "areaRadius:" + AreaRadius + ","
        + "bullet:" + Bullet + ","
        + "buffId:" + BuffId + ","
        + "ratio:" + Ratio + ","
        + "effect:" + Effect + ","
        + "audio:" + Audio + ","
        + "}";
    }
}
}

