
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class SkillData : Luban.BeanBase
{
    public SkillData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsNumber) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["des"].IsNumber) { throw new SerializationException(); }  Des = _buf["des"]; }
        { if(!_buf["animation"].IsNumber) { throw new SerializationException(); }  Animation = _buf["animation"]; }
        { if(!_buf["target_type"].IsNumber) { throw new SerializationException(); }  TargetType = _buf["target_type"]; }
        { if(!_buf["target_camp"].IsNumber) { throw new SerializationException(); }  TargetCamp = _buf["target_camp"]; }
        { if(!_buf["distance"].IsNumber) { throw new SerializationException(); }  Distance = _buf["distance"]; }
        { if(!_buf["speed"].IsNumber) { throw new SerializationException(); }  Speed = _buf["speed"]; }
        { if(!_buf["cooldown"].IsNumber) { throw new SerializationException(); }  Cooldown = _buf["cooldown"]; }
        { if(!_buf["duration"].IsNumber) { throw new SerializationException(); }  Duration = _buf["duration"]; }
        { var __json0 = _buf["skill_event"]; if(!__json0.IsArray) { throw new SerializationException(); } SkillEvent = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  SkillEvent.Add(__v0); }   }
        { var __json0 = _buf["hit_event"]; if(!__json0.IsArray) { throw new SerializationException(); } HitEvent = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  HitEvent.Add(__v0); }   }
    }

    public static SkillData DeserializeSkillData(JSONNode _buf)
    {
        return new SkillData(_buf);
    }

    /// <summary>
    /// 技能id
    /// </summary>
    public readonly int Id;
    public readonly int Name;
    public readonly string Icon;
    public readonly int Des;
    /// <summary>
    /// 动作<br/>1:skill1<br/>2:skill2<br/>...
    /// </summary>
    public readonly int Animation;
    /// <summary>
    /// 目标类型
    /// </summary>
    public readonly int TargetType;
    /// <summary>
    /// 1:友方2:敌人
    /// </summary>
    public readonly int TargetCamp;
    /// <summary>
    /// 攻击距离
    /// </summary>
    public readonly float Distance;
    /// <summary>
    /// 技能速度，影响动作速度、被融合的动作速度、技能事件的时间点，特效播放速度
    /// </summary>
    public readonly float Speed;
    /// <summary>
    /// 冷却时间
    /// </summary>
    public readonly float Cooldown;
    public readonly float Duration;
    /// <summary>
    /// 技能事件
    /// </summary>
    public readonly System.Collections.Generic.List<int> SkillEvent;
    /// <summary>
    /// 命中效果
    /// </summary>
    public readonly System.Collections.Generic.List<int> HitEvent;
   
    public const int __ID__ = -300302981;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "icon:" + Icon + ","
        + "des:" + Des + ","
        + "animation:" + Animation + ","
        + "targetType:" + TargetType + ","
        + "targetCamp:" + TargetCamp + ","
        + "distance:" + Distance + ","
        + "speed:" + Speed + ","
        + "cooldown:" + Cooldown + ","
        + "duration:" + Duration + ","
        + "skillEvent:" + Luban.StringUtil.CollectionToString(SkillEvent) + ","
        + "hitEvent:" + Luban.StringUtil.CollectionToString(HitEvent) + ","
        + "}";
    }
}
}

