
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbBattleInstance TbBattleInstance {get; }
    public TbBuffData TbBuffData {get; }
    public TbBuffEffectData TbBuffEffectData {get; }
    public TbBulletData TbBulletData {get; }
    public TbCharacterData TbCharacterData {get; }
    public TbEffect TbEffect {get; }
    public TbLanguage TbLanguage {get; }
    public TbPassiveSkillData TbPassiveSkillData {get; }
    public TbSkillAction TbSkillAction {get; }
    public TbSkillData TbSkillData {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbBattleInstance = new TbBattleInstance(loader("tbbattleinstance"));
        TbBuffData = new TbBuffData(loader("tbbuffdata"));
        TbBuffEffectData = new TbBuffEffectData(loader("tbbuffeffectdata"));
        TbBulletData = new TbBulletData(loader("tbbulletdata"));
        TbCharacterData = new TbCharacterData(loader("tbcharacterdata"));
        TbEffect = new TbEffect(loader("tbeffect"));
        TbLanguage = new TbLanguage(loader("tblanguage"));
        TbPassiveSkillData = new TbPassiveSkillData(loader("tbpassiveskilldata"));
        TbSkillAction = new TbSkillAction(loader("tbskillaction"));
        TbSkillData = new TbSkillData(loader("tbskilldata"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbBattleInstance.ResolveRef(this);
        TbBuffData.ResolveRef(this);
        TbBuffEffectData.ResolveRef(this);
        TbBulletData.ResolveRef(this);
        TbCharacterData.ResolveRef(this);
        TbEffect.ResolveRef(this);
        TbLanguage.ResolveRef(this);
        TbPassiveSkillData.ResolveRef(this);
        TbSkillAction.ResolveRef(this);
        TbSkillData.ResolveRef(this);
    }
}

}
