
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbBuffData
{
    private readonly System.Collections.Generic.Dictionary<int, BuffData> _dataMap;
    private readonly System.Collections.Generic.List<BuffData> _dataList;
    
    public TbBuffData(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, BuffData>(count);
        _dataList = new System.Collections.Generic.List<BuffData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BuffData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.BuffData.DeserializeBuffData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BuffData> DataMap => _dataMap;
    public System.Collections.Generic.List<BuffData> DataList => _dataList;

    public BuffData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public BuffData Get(int key) => _dataMap[key];
    public BuffData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

