
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbBuffEffectData
{
    private readonly System.Collections.Generic.Dictionary<int, BuffEffectData> _dataMap;
    private readonly System.Collections.Generic.List<BuffEffectData> _dataList;
    
    public TbBuffEffectData(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, BuffEffectData>(count);
        _dataList = new System.Collections.Generic.List<BuffEffectData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BuffEffectData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.BuffEffectData.DeserializeBuffEffectData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BuffEffectData> DataMap => _dataMap;
    public System.Collections.Generic.List<BuffEffectData> DataList => _dataList;

    public BuffEffectData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public BuffEffectData Get(int key) => _dataMap[key];
    public BuffEffectData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

