
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbBulletData
{
    private readonly System.Collections.Generic.Dictionary<int, BulletData> _dataMap;
    private readonly System.Collections.Generic.List<BulletData> _dataList;
    
    public TbBulletData(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, BulletData>(count);
        _dataList = new System.Collections.Generic.List<BulletData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BulletData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.BulletData.DeserializeBulletData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BulletData> DataMap => _dataMap;
    public System.Collections.Generic.List<BulletData> DataList => _dataList;

    public BulletData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public BulletData Get(int key) => _dataMap[key];
    public BulletData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

