
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbCharacterData
{
    private readonly System.Collections.Generic.Dictionary<int, CharacterData> _dataMap;
    private readonly System.Collections.Generic.List<CharacterData> _dataList;
    
    public TbCharacterData(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, CharacterData>(count);
        _dataList = new System.Collections.Generic.List<CharacterData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            CharacterData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.CharacterData.DeserializeCharacterData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, CharacterData> DataMap => _dataMap;
    public System.Collections.Generic.List<CharacterData> DataList => _dataList;

    public CharacterData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public CharacterData Get(int key) => _dataMap[key];
    public CharacterData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

