
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbPassiveSkillData
{
    private readonly System.Collections.Generic.Dictionary<int, PassiveSkillData> _dataMap;
    private readonly System.Collections.Generic.List<PassiveSkillData> _dataList;
    
    public TbPassiveSkillData(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, PassiveSkillData>(count);
        _dataList = new System.Collections.Generic.List<PassiveSkillData>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            PassiveSkillData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.PassiveSkillData.DeserializePassiveSkillData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, PassiveSkillData> DataMap => _dataMap;
    public System.Collections.Generic.List<PassiveSkillData> DataList => _dataList;

    public PassiveSkillData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public PassiveSkillData Get(int key) => _dataMap[key];
    public PassiveSkillData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

