
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbSkillAction
{
    private readonly System.Collections.Generic.Dictionary<int, SkillAction> _dataMap;
    private readonly System.Collections.Generic.List<SkillAction> _dataList;
    
    public TbSkillAction(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, SkillAction>(count);
        _dataList = new System.Collections.Generic.List<SkillAction>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            SkillAction _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.SkillAction.DeserializeSkillAction(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SkillAction> DataMap => _dataMap;
    public System.Collections.Generic.List<SkillAction> DataList => _dataList;

    public SkillAction GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public SkillAction Get(int key) => _dataMap[key];
    public SkillAction this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

